### ISSUE TITLE
Get started with Istio - add comment to CRs to easily show the changes

### ISSUE THREAD

**Issue by find-arka** [solo-io/workshops#169]
istio-workshops> istio-basics/labs/05/purchase-history-vs-all-v1-header-v2.yaml
```yaml
kind: VirtualService
metadata:
  name: purchase-history-vs
spec:
  hosts:
  - purchase-history.istioinaction.svc.cluster.local
  http:
#--- If user: Tom is present in incoming request header, go to purchase-history-v2 ---
  - match:
    - headers:
        user:
          exact: Tom
    route:
    - destination:
        host: purchase-history.istioinaction.svc.cluster.local
        subset: v2
        port:
          number: 8080
#--- Else, go to purchase-history-v1 ---
  - route:
    - destination:
        host: purchase-history.istioinaction.svc.cluster.local
        subset: v1
        port:
          number: 8080
      weight: 100
```
