### ISSUE TITLE
Gloo edge improvements

### ISSUE THREAD

**Issue by antonioberben** [solo-io/workshops#68]
- [ ]  Remove troubleshooting Tip

- [ ] Lab2: Create unauthenticated RateLimit for unauthenticated users

- [ ] Lab2: Add another Ratelimit for authenticated users based on a new claim like subcription (values: gold, platinium, etc). 

- [ ] Lab6: For the AuthN scenario, it needs to be moved to Lab2.

- [ ] Lab6: Remove the extractor for the id token since it is already taken before.

- [ ] Improve WAF sample. Block a huge payload with POST to bookinfo for the case of unauthenticated users

- [ ] Improve WAF sample. Add client-agent check

- [ ] Add to response transformations. Take a header from the request and add it into the response.

- [ ] Improve response transformations. Take the 401 and transform the body in the response.

- [ ] Add something with regex
```
transformationTemplate:
                           passthrough: {}
                           extractors:
                               originalClientIpAddress:
                                   header: 'x-forwarded-for'
                                   regex: '([^,\n]*).*$'
```

- [ ] Move delegation after LAB1. Delegate to different routeTables to different teams /secure  with reoutetable1 to be managed by team1. Keep the route  /  at the VS level to show that we can also keep things in the VS

- [ ] Move RT to a specific namespace like team1 so they can see it can be in a different namespace.

- [ ] Use label selectors for the RT so we can show that the name is note totally required

- [ ] Lab6. Remove the extractor for the id token since it already taken before. → use the extauth > authconfig > oidc > headers > idTokenHeader to forward it upstream
