### ISSUE TITLE
[Gloo Edge - Instruqt - Lab 2] VirtualService doesn't match diagram

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/workshops#89]
The diagram for Lab 2 indicates that both v2 and v3 will be routed to. The VS doesn't match the diagram. It only routes to v2 and is confusing to users.

<img width="789" alt="Screen Shot 2021-11-02 at 5 44 45 PM" src="https://user-images.githubusercontent.com/52334260/139956129-94229bbc-f337-474a-ba3e-4b64838b0802.png">

```
kubectl apply -f - <<EOF
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: demo
  namespace: gloo-system
spec:
  sslConfig:
    secretRef:
      name: upstream-tls
      namespace: gloo-system
  virtualHost:
    domains:
      - '*'
    routes:
      - matchers:
          - prefix: /not-secured
        delegateAction:
          selector:
            namespaces:
              - team1
            labels:
              application-owner: team1
      - matchers:
          - prefix: /
# ------------------- OIDC - Only applied to this matcher -------------------
        options:
          extauth:
            configRef:
              name: oauth
              namespace: gloo-system
# ---------------------------------------------------------------------------
        routeAction:
          single:
            upstream:
              name: bookinfo-productpage-9080
              namespace: gloo-system
EOF
```
