### ISSUE TITLE
[Gloo Edge - Instruqt - Lab 2] curl verification fails with 404 not found after enabling TLS

### ISSUE THREAD

**Issue by drew-solo** [solo-io/workshops#99]
After adding TLS configuration in Lab 2, command "curl -k $APP_URL/not-secured/get" fails with "404 Not Found".

<img width="1090" alt="Instruqt-Lab2-error" src="https://user-images.githubusercontent.com/91756318/141534995-6cff04b1-2682-4833-9c29-de81eb049405.png">

**Comment by jmunozro** [comment]
Not able to reproduce
![image](https://user-images.githubusercontent.com/35881711/142181497-7d482dc2-0d4c-4753-8568-30fbf8ec51a0.png)

**Comment by murphye** [comment]
There are no labels on the `RouteTable`

```
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: httpbin-routetable
  namespace: team1
spec:
  routes:
    - matchers:
        - prefix: /not-secured
      options:
        prefixRewrite: '/'
      routeAction:
          single:
            upstream:
              name: team1-httpbin-8000
              namespace: gloo-system
```

The `vs-with-tls.yaml` has a label reference

```
            labels:
              application-owner: team1
```
